server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      #将微服务挡在网关之后
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates: #断言
            - Path=/payment/discovery/**         # 断言，路径相匹配的进行路由
            #- After=2020-05-27T11:53:03.924+08:00[Asia/Shanghai] #表示在此之后访问才有效果
            #- Cookie=username,tia #用户名和正则表达式 --cookie "username=tia"
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数(正数)的正则表达式 -H "X-Request-Id:123"

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka