server:
  port: 7001

eureka:
  instance:
    #hostname: localhost #eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #表示自己端是注册中心，职责是维护服务实例而非检索服务
    service-url: #设置与eureka server交互的地址，注册服务和查询服务都需要依赖此地址
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    enable-self-preservation: false